---
- name: install Hive packages
  apt: name={{ item }} state=installed
  with_items:
    - hive
    - hive-metastore
    - hive-server2
    - libmysql-java
  tags:
    - install

- name: setup mysql java connector
  file: src=/usr/share/java/mysql-connector-java.jar dest=/usr/lib/hive/lib/libmysql-java.jar state=link
  tags:
    - install

- name: create metastore database
  mysql_db: name=metastore state=present login_user=root login_password={{ mysql_root_password }}
  tags:
    - install

- name: create hive metastore user in mysql
  mysql_user: >
    name={{ hive_metastore_user }} password={{ hive_metastore_password }} 
    priv=metastore.*:ALL host=localhost state=present
    login_user=root login_password={{ mysql_root_password }}
  tags:
    - install

- name: init metastore schema
  shell: >
    mysql --user=root --password={{ mysql_root_password }} 
    metastore < {{ hive_metastore_schema }}
    # ignore error if duplicate exists
  ignore_errors: yes
  tags:
    - install

- name: add user hive to group hadoop to allow writing to hdfs://
  user: name={{ hive_user }} groups={{ hadoopgroup }} append=yes
  tags:
    - install

- name: configure hive-site.xml
  template: src=conf/hive-site.xml.j2 dest={{ hive_conf_dir }}/hive-site.xml
  notify:
    - restart hive
  tags:
    - configure
