---

- name: gather facts
  hosts: all
  gather_facts: yes
  tasks:
   - group_by: key={{ansible_os_family}}
   - debug: msg="{{groups}}"

- name: apply common configuration to all nodes
  sudo: yes
  hosts: all
  roles:
    - common
  any_errors_fatal: yes

- name: set up master host for convenience
  sudo: yes
  hosts: master
  roles:
    - goodies
  any_errors_fatal: yes

- name: create non-root clusteruser user
  sudo: yes
  hosts: all
  roles:
    - clusteruser_common
  any_errors_fatal: yes

- name: setup passwordless SSH for clusteruser - donor key
  sudo: yes
  hosts: master
  roles: 
    - { role: sshkey_donor }
  any_errors_fatal: yes

- name: setup passwordless SSH for clusteruser - accept key
  sudo: yes
  hosts: workers
  roles:
    - { role: sshkey_acceptor }
  any_errors_fatal: yes

- name: setup passwordless SSH for user root - donor key
  sudo: yes
  hosts: master
  roles:
    - { role: sshkey_donor, clusteruser: root, clusteruser_home: '/root' }
  any_errors_fatal: yes

- name: setup passwordless SSH for user root - accept key
  sudo: yes
  hosts: workers
  roles:
    - { role: sshkey_acceptor, clusteruser: root, clusteruser_home: '/root' }
  any_errors_fatal: yes

- name: setup nfs master
  sudo: yes
  hosts: master
  roles: 
    - { role: nfs_server, when: install_mpi }

- name: setup nfs clients
  sudo: yes
  hosts: workers
  roles: 
    - { role: nfs_client, when: install_mpi }

- name: setup mpi cluster
  sudo: yes
  hosts: all
  roles:
    - { role: openmpi, when: install_mpi }

- name: install SBT
  sudo: yes
  hosts: master
  roles:
    - { role: sbt, when: install_spark }
  any_errors_fatal: yes

- name: install Scala
  sudo: yes
  hosts: master
  roles:
    - { role: scala, when: install_spark }
  any_errors_fatal: yes

- name: setup HDFS namenode
  sudo: yes
  hosts: master
  roles:
    - { role: hdfs_namenode, when: install_spark or install_mapred or install_mesos or install_tachyon }
  any_errors_fatal: yes

- name: setup HDFS datanodes
  sudo: yes
  hosts: workers
  roles:
    - { role: hdfs_datanode, when: install_spark or install_mapred or install_mesos or install_tachyon }
  any_errors_fatal: yes

- name: deploy standalone Spark
  sudo: yes
  hosts: all
  roles:
    - { role: spark_standalone, when: install_spark }
  any_errors_fatal: yes

- name: install Mesos
  sudo: yes
  hosts: all
  roles:
    - { role: mesos, when: install_mesos }
  any_errors_fatal: yes

- name: deploy Spark on Mesos
  sudo: yes
  hosts: master
  roles:
    - { role: spark_mesos, when: install_mesos and install_spark }
  any_errors_fatal: yes

- name: install mysql on Hive master
  sudo: yes
  hosts: master
  roles:
    - { role: mysql_server, when: install_hive }
  any_errors_fatal: yes

- name: install Hive
  sudo: yes
  hosts: master
  roles:
    - { role: hive, when: install_hive }
  any_errors_fatal: yes

- name: deploy Tachyon
  sudo: yes
  hosts: all
  roles:
    - { role: tachyon, when: install_tachyon }
  any_errors_fatal: yes

- name: setup YARN resourcemanager
  sudo: yes
  hosts: master
  roles:
    - { role: yarn_resourcemanager, when: install_mapred }
  any_errors_fatal: yes

- name: setup YARN nodemanagers
  sudo: yes
  hosts: workers
  roles:
    - { role: yarn_nodemanager, when: install_mapred }
  any_errors_fatal: yes

- name: install Cassandra
  sudo: yes
  hosts: all
  roles:
    - { role: cassandra, when: install_cassandra }

- include: tests/integration-tests.yml



